### ISSUE TITLE
Action fails regularly due to ETIMEDOUT and ECONNRESET

### ISSUE THREAD

**Issue by ZacSweers** [gradle/wrapper-validation-action#40]
Example runs:

https://github.com/square/anvil/pull/266/checks?check_run_id=2589215352

https://github.com/square/anvil/pull/266/checks?check_run_id=2589215611

I've seen this flakey behavior happen somewhat often in the past few weeks, not sure what else is going on so filing this as an FYI.

**Comment by JLLeitschuh** [comment]
This may be the same as #33

Hopefully, #39 having been merged will resolve this. @eskatos can you perform a release to see if that helps resolve this issue for our users?

**Comment by ZacSweers** [comment]
Is there anything else needed for a release that I could maybe help with? This makes most of our workflows unusable

**Comment by JLLeitschuh** [comment]
@ZacSweers I believe that you can try out this action from a commit hash. You may want to give that a shot as a stopgap?

**Comment by ZacSweers** [comment]
Using ef08c6885017f258a11d59e0da103ed39424aa6b appears to resolve things for us. I'd recommend a new 1.x release tag to de-flake things for folks, we were definitely considering dropping this otherwise and I'm not sure how willing folks are to point at a direct sha

**Comment by JLLeitschuh** [comment]
Should be published now as `v1`

**Comment by ZacSweers** [comment]
We're still seeing this unfortunately, albeit less often and just as this

```
Run gradle/wrapper-validation-action@v1
Error: read ECONNRESET
```

**Comment by ZacSweers** [comment]
Here's an example run https://github.com/ZacSweers/MoshiX/pull/128/checks?check_run_id=2921425588

**Comment by ZacSweers** [comment]
This happens pretty consistently across the projects I work on, unfortunately I think we're going to have to remove this action as a result as it's a reliability issue

**Comment by JLLeitschuh** [comment]
Unfortunately, we don't have enough information at this time to understand what's causing this issue.

Are you using self-hosted runners, or runners hosted by GH?

**Comment by ZacSweers** [comment]
I see this often on GH hosted runners, often in the square/anvil repo

**Comment by JLLeitschuh** [comment]
@eskatos is there any way to add additional log output on failure so that we can work on understanding the root cause?

**Comment by nkvaratskhelia** [comment]
This is the error that I'm getting:
Error: connect ETIMEDOUT 104.18.164.99:443

**Comment by JLLeitschuh** [comment]
> Github hosted actions here. When the action fails with this error it fails across all active runs around the same time. About 30 minutes ago 3 runs failed simultaneously. Retried each about 20 minutes ago and they all passed.

That seems like something that absolutely indicates a cloudflare issue.

**Comment by JLLeitschuh** [comment]
Okay, all this finally sent me down the right path, I think I may have finally figured out what's going on here. It looks like our Cloudflare WAF is being triggered every once and awhile randomly and is causing a bunch of users connections to fail when it does. I need to talk to @eskatos about how we want to mitigate this issue. Thanks everyone for helping us figure out what was going wrong here.


<img width="1123" alt="Screen Shot 2021-09-22 at 10 40 12 AM" src="https://user-images.githubusercontent.com/1323708/134365479-e272734d-0be3-4d62-baaf-c28cba618267.png">

**Comment by JLLeitschuh** [comment]
The fix has been implemented.

Please let us know if any of you continue to experience these problems. I hope this will fix the issue, but we have some additional things we can fiddle with if this continues to be a problem.

---

FOR INTERNAL TRACKING (not public): https://github.com/gradle/gradle-private/issues/3435

**Comment by gnarea** [comment]
I've been running into this issue occasionally ever since I integrated this action, but today it's been happening like 60% of the time on macOS on CI (CI also runs on Windows and Linux, but both seem fine).

I recently upgraded to Gradle 7, in case that's relevant.

**Comment by JLLeitschuh** [comment]
So, I've checked, and it's not our WAF causing theses issues. I'm not certain what would be causing these issues otherwise.

**Comment by nhouser9** [comment]
Running into the same issue today. Any updates on this?

**Comment by ouchadam** [comment]
also seeing this issue a few times every day, retrying tends to work straight away

![2021-11-24T11:22:49,356896107+00:00](https://user-images.githubusercontent.com/1848238/143229381-3dd30803-85a5-49b5-bfdc-b56f493db3b4.png)



https://github.com/vector-im/element-android/actions/workflows/gradle-wrapper-validation.yml?query=is%3Afailure

**Comment by jrodbx** [comment]
Seeing this a lot on Paparazzi builds, mainly with Windows workers
Example run: https://github.com/cashapp/paparazzi/runs/4316309670?check_suite_focus=true

**Comment by The-Code-Monkey** [comment]
Is there any further update on this as it keeps failing sporadically on both windows-2022 and ubuntu-20.04 action runs.

**Comment by DanySK** [comment]
I also keep getting CI failures due to this issue: `Error: connect ETIMEDOUT 104.18.165.99:443`.
This might be silly, but since relaunching usually fixes, I wonder whether just allowing for three retries or so could be helpful. In the end, connection timeouts may happen, unless some destination is unreachable it may make sense not to fail immediately.

**Comment by JLLeitschuh** [comment]
We do have retry logic enabled.
https://github.com/gradle/wrapper-validation-action/blob/84d7e182ae7c7a37f200c184f64038fb0e62dd7d/src/checksums.ts#L6

That being said, I have no evidence that it's actually working. A PR to improve debug logging from the community would be welcomed openly. Especially if it were implemented such that the additional logging was only printed when the build was going to fail anyways. I'd prefer to not make the action more chatty than it needs to be when it's not going to fail. I think the biggest problem we currently have is a severe lack of visibility. As such it makes it really difficult to figure out a root cause for these issues.

**Comment by madisp** [comment]
still happens to this day, I've been unable to have a valid build after multiple retries :(

**Comment by JLLeitschuh** [comment]
Are you running this on self-hosted runners, or is this running on GitHub's infrastructure?

**Comment by madisp** [comment]
it was on GH infra, but it may have been an older fixed version of the action that suddenly started failing.

Upgraded from `8d49e559aae34d3e0eb16cde532684bc9702762b` to `ccb4328a959376b642e027874838f60f8e596de3`, will report if it's still happening.

Out of curiosity, why is the Action making any request at all, wouldn't it make sense to store the valid hash-version pairs inside the action itself and only hit network if a local entry doesn't exist?

**Comment by JLLeitschuh** [comment]
Not a bad idea. @bigdaz @eskatos what are your thoughts?

**Comment by DanySK** [comment]
@bigdaz it makes a lot of sense

**Comment by JLLeitschuh** [comment]
>  The results could be cached in the GitHub Actions cache

The only thing I would be slightly concerned about is ensuring that it is impossible for an attacker to tamper with the cache prior to this action running.

**Comment by LunNova** [comment]
Is there a reason for gradle not to add the checksums inline in https://services.gradle.org/versions/all instead of requiring fetching a separate file per checksum?

**Comment by bigdaz** [comment]
This should be fixed by #167

**Comment by MaximDzhezhelo** [comment]
still happens to this day, I've been unable to have a valid build after multiple retries :(

**Comment by leinardi** [comment]
From what I can read [here](https://github.com/gradle/actions/blob/main/docs/wrapper-validation.md)

> Starting with v4 the `setup-gradle` action will automatically [perform wrapper validation](../docs/setup-gradle.md#gradle-wrapper-validation)
> on each execution.
> 
> If you are using `setup-gradle` in your workflows, it is unlikely that you will need to use the `wrapper-validation` action.

**Comment by bigdaz** [comment]
> still happens to this day, I've been unable to have a valid build after multiple retries :(

@MaximDzhezhelo What version of the action are you using? This issue should have been fixed.

Note that `gradle/wrapper-validation-action` has been replaced by `gradle/actions/wrapper-validation`. 
Can you please try with `gradle/actions/wrapper-validation@v4`?

**Comment by MaximDzhezhelo** [comment]
@bigdaz I am currently using `gradle/actions/wrapper-validation@v3.` However, I don't quite understand why you're recommending v4, considering the latest version in the documentation is v3.5.0. 
Could you clarify?

**Comment by bigdaz** [comment]
The last release of the deprecated `gradle/wrapper-validation-action` is `v3.5.0`.
But development continues on [gradle/actions/wrapper-validation](https://github.com/gradle/actions/blob/main/docs/wrapper-validation.md). The most recent release is https://github.com/gradle/actions/releases/tag/v4.2.2.
